blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/mitambuch/steaksoap/discussions
    about: Ask questions or start a discussion instead of opening an issue.
